# Generated by Django 3.0.3 on 2020-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20200212_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
