# Generated by Django 3.0.3 on 2020-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_pdf_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='pdf_text',
            new_name='text',
        ),
    ]
